// =========================================================================
// BAZA DANYCH SŁYNNYCH MIEJSC ZE ŚWIATA (ZDJĘCIA LOKALNE)
// =========================================================================
const FAMOUS_PLACES_DB = [
    {
        name: "Wieża Eiffla (Paryż, Francja)",
        lat: 48.8584,
        lng: 2.2945,
        continent: "Europa",
        category: "Architektura / Symbol",
        easy: true,
        img: "img/eiffel_tower.jpg",
        license: "Unsplash / CC",
        clue: "Stalowa wieża wybudowana na Wystawę Światową w 1889 roku nad rzeką Sekwaną.",
        desc: "Monumentalna wieża kratowa na Polu Marsowym w Paryżu o wysokości 330 metrów, najsłynniejszy symbol Francji."
    },
    {
        name: "Koloseum (Rzym, Włochy)",
        lat: 41.8902,
        lng: 12.4922,
        continent: "Europa",
        category: "Starożytność / Amfiteatr",
        easy: true,
        img: "img/colosseum.jpg",
        license: "Unsplash / CC",
        clue: "Najsłynniejszy amfiteatr cesarzy rzymskich i walk gladiatorów w Wiecznym Mieście.",
        desc: "Amfiteatr Flawiuszy wzniesiony w I wieku n.e. w sercu Rzymu. Mógł pomieścić do 50 tysięcy widzów."
    },
    {
        name: "Akropol Ateński (Ateny, Grecja)",
        lat: 37.9715,
        lng: 23.7257,
        continent: "Europa",
        category: "Starożytność / Świątynia",
        easy: true,
        img: "img/acropolis.jpg",
        license: "Unsplash / CC",
        clue: "Wzgórze ze świątynią Partenon górujące nad stolicą i kolebką demokracji.",
        desc: "Wapienne wzgórze w Atenach ze słynnym Partenonem poświęconym bogini Atenie, zbudowanym w V wieku p.n.e."
    },
    {
        name: "Big Ben i Pałac Westminsterski (Londyn, Wielka Brytania)",
        lat: 51.5007,
        lng: -0.1246,
        continent: "Europa",
        category: "Architektura / Parlament",
        easy: true,
        img: "img/big_ben.jpg",
        license: "Unsplash / CC",
        clue: "Neogotycka wieża zegarowa nad Tamizą w stolicy Wielkiej Brytanii.",
        desc: "Słynna wieża zegarowa Elizabeth Tower (potocznie Big Ben) przy siedzibie brytyjskiego parlamentu."
    },
    {
        name: "Zamek w Malborku (Polska)",
        lat: 54.0398,
        lng: 19.028,
        continent: "Europa",
        category: "Średniowiecze / Twierdza",
        easy: false,
        img: "img/malbork.jpg",
        license: "Unsplash / CC",
        clue: "Największy zamek ceglany na świecie, dawna stolica Zakonu Krzyżackiego.",
        desc: "Potężna twierdza krzyżacka nad rzeką Nogat, wpisana na listę światowego dziedzictwa UNESCO."
    },
    {
        name: "Pałac Kultury i Nauki (Warszawa, Polska)",
        lat: 52.2319,
        lng: 21.0067,
        continent: "Europa",
        category: "Architektura / Wieżowiec",
        easy: true,
        img: "img/warszawa.jpg",
        license: "AI Generated HD",
        clue: "Charakterystyczny socrealistyczny wieżowiec z zegarem milenijnym w centrum stolicy Polski.",
        desc: "Najbardziej rozpoznawalny budynek Warszawy o wysokości 237 metrów, otoczony nowoczesnymi drapaczami chmur nad Wisłą."
    },
    {
        name: "Krzywa Wieża w Pizie (Włochy)",
        lat: 43.723,
        lng: 10.3966,
        continent: "Europa",
        category: "Architektura / Dzwonnica",
        easy: true,
        img: "img/pisa.jpg",
        license: "Unsplash / CC",
        clue: "Słynna romańska dzwonnica o wyraźnym przechyleniu na Polu Cudów w Toskanii.",
        desc: "Marmurowa dzwonnica katedralna w Pizie, która zaczęła się przechylać niemal natychmiast po rozpoczęciu budowy w 1173 roku."
    },
    {
        name: "Stonehenge (Wiltshire, Anglia)",
        lat: 51.1789,
        lng: -1.8262,
        continent: "Europa",
        category: "Prehistoria / Megality",
        easy: true,
        img: "img/stonehenge.jpg",
        license: "Unsplash / CC",
        clue: "Prehistoryczny kamienny krąg w południowej Anglii powiązany z przesileniem letnim.",
        desc: "Megalityczna budowla z epoki neolitu i brązu, składająca się z monumentalnych stojących głazów."
    },
    {
        name: "Zamek Neuschwanstein (Bawaria, Niemcy)",
        lat: 47.5576,
        lng: 10.7498,
        continent: "Europa",
        category: "Architektura / Zamek",
        easy: true,
        img: "img/neuschwanstein.jpg",
        license: "Unsplash / CC",
        clue: "Bajkowy zamek króla Ludwika II w bawarskich Alpach, inspiracja dla Disneya.",
        desc: "XIX-wieczny neoromański zamek rycerski wzniesiony na urwistej skale w południowej Bawarii."
    },
    {
        name: "Gejzer Strokkur (Islandia)",
        lat: 64.3127,
        lng: -20.3008,
        continent: "Europa",
        category: "Cuda Natury / Wulkany",
        easy: false,
        img: "img/strokkur.jpg",
        license: "Unsplash / CC",
        clue: "Wybuchający co 5-10 minut wrzątkiem gejzer w krainie lodu i ognia.",
        desc: "Bardzo aktywny gejzer w dolinie Haukadalur na Islandii, wyrzucający słup gorącej wody na wysokość do 30 metrów."
    },
    {
        name: "Tadż Mahal (Agra, Indie)",
        lat: 27.1751,
        lng: 78.0421,
        continent: "Azja",
        category: "Mauzoleum / Architektura",
        easy: true,
        img: "img/taj_mahal.jpg",
        license: "Unsplash / CC",
        clue: "Mauzoleum z białego marmuru wzniesione przez cesarza Szahdżahana z miłości do żony.",
        desc: "Jeden z siedmiu nowych cudów świata, klejnot sztuki muzułmańskiej w Indiach nad rzeką Jamuna."
    },
    {
        name: "Wielki Mur Chiński (Chiny)",
        lat: 40.4319,
        lng: 116.5704,
        continent: "Azja",
        category: "Fortyfikacja / Starożytność",
        easy: true,
        img: "img/great_wall.jpg",
        license: "Unsplash / CC",
        clue: "Tysiąckilometrowy system obronny wznoszony przez wieki na północy Chin.",
        desc: "Zbiorcza nazwa systemów obronnych z ziemi i kamienia, ciągnących się przez tysiące kilometrów wzdłuż północnych granic Chin."
    },
    {
        name: "Góra Fudżi (Honsiu, Japonia)",
        lat: 35.3606,
        lng: 138.7274,
        continent: "Azja",
        category: "Cuda Natury / Wulkan",
        easy: true,
        img: "img/mount_fuji.jpg",
        license: "Unsplash / CC",
        clue: "Święty, ośnieżony stratowulkan o idealnie symetrycznym stożku w Japonii.",
        desc: "Czynny stratowulkan i najwyższy szczyt Japonii (3776 m n.p.m.), symbol i święta góra kultury japońskiej."
    },
    {
        name: "Petra – Skarbiec Al-Chazna (Jordania)",
        lat: 30.3285,
        lng: 35.4444,
        continent: "Azja",
        category: "Starożytność / Miasto Skalne",
        easy: true,
        img: "img/petra.jpg",
        license: "Wikimedia CC",
        clue: "Starożytne miasto Nabatejczyków wykute w różowych piaskowcach pustyni.",
        desc: "Ruiny starożytnego miasta wykutego w skałach wąwozu Siq w południowej Jordanii."
    },
    {
        name: "Burdż Chalifa (Dubaj, ZEA)",
        lat: 25.1972,
        lng: 55.2744,
        continent: "Azja",
        category: "Architektura / Wieżowiec",
        easy: true,
        img: "img/burj_khalifa.jpg",
        license: "Unsplash / CC",
        clue: "Najwyższy wieżowiec i budowla wzniesiona kiedykolwiek przez człowieka (828 m).",
        desc: "Superwieżowiec w Dubaju o wysokości 828 metrów, liczący 163 piętra użytkowe."
    },
    {
        name: "Angkor Wat (Siem Reap, Kambodża)",
        lat: 13.4125,
        lng: 103.867,
        continent: "Azja",
        category: "Starożytność / Kompleks Świątynny",
        easy: false,
        img: "img/angkor_wat.jpg",
        license: "Unsplash / CC",
        clue: "Największy kompleks świątynny na Ziemi, dawne serce Imperium Khmerskiego.",
        desc: "Monumentalna świątynia hinduistyczno-buddyjska wzniesiona w XII wieku w dżungli Kambodży."
    },
    {
        name: "Zatoka Ha Long (Wietnam)",
        lat: 20.9101,
        lng: 107.1839,
        continent: "Azja",
        category: "Cuda Natury / Kras",
        easy: false,
        img: "img/halong_bay.jpg",
        license: "Unsplash / CC",
        clue: "Tysiące wapiennych wysepek i ostańców wyrastających ze szmaragdowych wód Zatoki Tonkińskiej.",
        desc: "Malowniczy krasowy krajobraz wysp i jaskiń w północnym Wietnamie wpisany na listę UNESCO."
    },
    {
        name: "Piramidy w Gizie i Sfinks (Kair, Egipt)",
        lat: 29.9792,
        lng: 31.1342,
        continent: "Afryka",
        category: "Starożytność / Piramidy",
        easy: true,
        img: "img/giza_pyramids.jpg",
        license: "Unsplash / CC",
        clue: "Piramida Cheopsa i monumentalny posąg lwa z ludzką twarzą na skraju Sahary.",
        desc: "Jedyne zachowane do dziś z siedmiu starożytnych cudów świata, grobowce faraonów sprzed 4500 lat."
    },
    {
        name: "Wodospady Wiktorii (Zambia / Zimbabwe)",
        lat: -17.9243,
        lng: 25.8572,
        continent: "Afryka",
        category: "Cuda Natury / Wodospad",
        easy: false,
        img: "img/victoria_falls.jpg",
        license: "Unsplash / CC",
        clue: "„Dym, który grzmi” – potężny uskok rzeki Zambezi o szerokości ponad 1,7 km.",
        desc: "Jeden z najwspanialszych wodospadów świata na granicy Zambii i Zimbabwe na rzece Zambezi."
    },
    {
        name: "Góra Stołowa (Kapsztad, RPA)",
        lat: -33.9628,
        lng: 18.4098,
        continent: "Afryka",
        category: "Cuda Natury / Płaskowyż",
        easy: false,
        img: "img/table_mountain.jpg",
        license: "Unsplash / CC",
        clue: "Płaska jak stół góra z piaskowca górująca nad Zatoką Stołową w Afryce Południowej.",
        desc: "Charakterystyczny szczyt o płaskiej wierzchowinie w Kapsztadzie, otoczony unikalną florą przylądkową."
    },
    {
        name: "Statua Wolności (Nowy Jork, USA)",
        lat: 40.6892,
        lng: -74.0445,
        continent: "Ameryka Północna",
        category: "Pomnik / Symbol",
        easy: true,
        img: "img/statue_of_liberty.jpg",
        license: "Unsplash / CC",
        clue: "Monumentalny posąg z pochodnią na Liberty Island, dar narodu francuskiego dla USA.",
        desc: "Neoklasycystyczny posąg na wyspie w porcie Nowego Jorku, symbol wolności i demokracji."
    },
    {
        name: "Wielki Kanion Kolorado (Arizona, USA)",
        lat: 36.1069,
        lng: -112.1129,
        continent: "Ameryka Północna",
        category: "Cuda Natury / Kanion",
        easy: true,
        img: "img/grand_canyon.jpg",
        license: "Unsplash / CC",
        clue: "Olbrzymi przełom rzeki Kolorado odsłaniający miliardy lat historii geologicznej.",
        desc: "Jeden z najgłębszych i najbardziej spektakularnych kanionów na świecie o długości 446 km w stanie Arizona."
    },
    {
        name: "Most Golden Gate (San Francisco, Kalifornia, USA)",
        lat: 37.8199,
        lng: -122.4783,
        continent: "Ameryka Północna",
        category: "Inżynieria / Most",
        easy: true,
        img: "img/golden_gate.jpg",
        license: "Unsplash / CC",
        clue: "Pomarańczowy most wiszący spowity pacyficzną mgłą nad cieśniną w Kalifornii.",
        desc: "Słynny most wiszący w San Francisco pomalowany na charakterystyczny kolor International Orange."
    },
    {
        name: "Wodospad Niagara (USA / Kanada)",
        lat: 43.08,
        lng: -79.071,
        continent: "Ameryka Północna",
        category: "Cuda Natury / Wodospad",
        easy: true,
        img: "img/niagara.jpg",
        license: "Unsplash / CC",
        clue: "Najpotężniejszy pod względem przepływu wodospad Ameryki Północnej na granicy z Kanadą.",
        desc: "Kompleks wodospadów na rzece Niagara łączącej jeziora Erie i Ontario."
    },
    {
        name: "Chichén Itzá – El Castillo (Jukatan, Meksyk)",
        lat: 20.6843,
        lng: -88.5678,
        continent: "Ameryka Północna",
        category: "Starożytność / Piramida Majów",
        easy: true,
        img: "img/chichen_itza.jpg",
        license: "Unsplash / CC",
        clue: "Schodkowa piramida boga Kukulkana w prekolumbijskim mieście Majów.",
        desc: "Słynna piramida Majów na półwyspie Jukatan w Meksyku, zaprojektowana zgodnie z astronomicznym kalendarzem."
    },
    {
        name: "Machu Picchu (Andy, Peru)",
        lat: -13.1631,
        lng: -72.545,
        continent: "Ameryka Południowa",
        category: "Starożytność / Miasto Inków",
        easy: true,
        img: "img/machu_picchu.jpg",
        license: "Unsplash / CC",
        clue: "Tajemnicze zaginione miasto Inków położone na grzbiecie górskim w Andach.",
        desc: "Najlepiej zachowane miasto Inków z XV wieku, ukryte na wysokości 2430 m n.p.m. nad doliną rzeki Urubamba."
    },
    {
        name: "Chrystus Odkupiciel na Corcovado (Rio de Janeiro, Brazylia)",
        lat: -22.9519,
        lng: -43.2105,
        continent: "Ameryka Południowa",
        category: "Pomnik / Symbol",
        easy: true,
        img: "img/christ_redeemer.jpg",
        license: "Unsplash / CC",
        clue: "30-metrowy posąg z rozpostartymi ramionami górujący nad Zatoką Guanabara.",
        desc: "Monolityczny posąg Jezusa Chrystusa na szczycie góry Corcovado w Rio de Janeiro."
    },
    {
        name: "Wodospady Iguazú (Argentyna / Brazylia)",
        lat: -25.6953,
        lng: -54.4367,
        continent: "Ameryka Południowa",
        category: "Cuda Natury / Wodospad",
        easy: false,
        img: "img/iguazu_falls.jpg",
        license: "Unsplash / CC",
        clue: "Ponad 275 kaskad wodnych w sercu lasu deszczowego z Diabelskim Gardłem.",
        desc: "Jeden z najpotężniejszych systemów wodospadów na świecie na rzece Iguazú na granicy argentyńsko-brazylijskiej."
    },
    {
        name: "Opera w Sydney (Australia)",
        lat: -33.8568,
        lng: 151.2153,
        continent: "Australia i Oceania",
        category: "Architektura / Teatr",
        easy: true,
        img: "img/sydney_opera.jpg",
        license: "Unsplash / CC",
        clue: "Ekspresjonistyczny budynek opery przypominający białe muszle lub żagle w porcie Sydney.",
        desc: "Projekt duńskiego architekta Jørna Utzona, arcydzieło architektury XX wieku wpisane na listę UNESCO."
    },
    {
        name: "Uluru / Ayers Rock (Australia Centralna)",
        lat: -25.3444,
        lng: 131.0369,
        continent: "Australia i Oceania",
        category: "Cuda Natury / Monolit",
        easy: true,
        img: "img/uluru.jpg",
        license: "Unsplash / CC",
        clue: "Święta dla Aborygenów olbrzymia czerwona skała z piaskowca w sercu pustynnego Outbacku.",
        desc: "Monumentalna formacja skalna wznosząca się na 348 metrów ponad płaską pustynię w środkowej Australii."
    },
    {
        name: "Fiord Milford Sound (Nowa Zelandia)",
        lat: -44.6414,
        lng: 167.8975,
        continent: "Australia i Oceania",
        category: "Cuda Natury / Fiord",
        easy: false,
        img: "img/milford_sound.jpg",
        license: "Unsplash / CC",
        clue: "Zatoka polodowcowa z ikonicznym szczytem Mitre Peak na Wyspie Południowej Nowej Zelandii.",
        desc: "Jeden z najbardziej deszczowych i spektakularnych fiordów świata, nazwany przez Rudyarda Kiplinga „ósmym cudem świata”."
    },
    {
        name: "Kapadocja / Dolina Goreme (Turcja)",
        lat: 38.6431,
        lng: 34.8289,
        continent: "Azja",
        category: "Geologia / Formacje tufowe",
        easy: false,
        img: "img/cappadocia.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Baśniowy krajobraz stożków wulkanicznych, podziemnych miast i setek balonów o wschodzie słońca w Anatolii.",
        desc: "Region w środkowej Turcji uformowany przez erozję popiołów wulkanicznych (tuf). Od starożytności ludzie drążyli tu domy, kościoły i wielopoziomowe podziemne schronienia."
    },
    {
        name: "Pamukkale / Bawełniany Zamek (Turcja)",
        lat: 37.925,
        lng: 29.1214,
        continent: "Azja",
        category: "Geologia / Tarasy trawertynowe",
        easy: false,
        img: "img/pamukkale.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Śnieżnobiałe wapienne tarasy z turkusową wodą termalną tuż pod ruinami starożytnego Hierapolis.",
        desc: "Wody termalne bogate w wodorowęglan wapnia spływające po zboczu góry stworzyły kaskadę naturalnych basenów i stalaktytów przypominających bawełnianą twierdzę."
    },
    {
        name: "Klasztory w Meteorach (Grecja)",
        lat: 39.7217,
        lng: 21.6306,
        continent: "Europa",
        category: "Klasztory / Formacje skalne",
        easy: false,
        img: "img/meteora.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Średniowieczne prawosławne monastery wzniesione na szczytach pionowych, niedostępnych wież z piaskowca w Tesalii.",
        desc: "Klasztory dosłownie 'zawieszone w powietrzu' (gr. meteora), budowane od XIV wieku przez mnichów uciekających przed najazdami tureckimi. Dostęp zapewniały liny i kołowroty."
    },
    {
        name: "Mont Saint-Michel (Normandia, Francja)",
        lat: 48.636,
        lng: -1.5115,
        continent: "Europa",
        category: "Średniowiecze / Opactwo pływowe",
        easy: false,
        img: "img/mont_saint_michel.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Gotyckie benedyktyńskie opactwo na skalistej wysepce, która podczas przypływu staje się całkowicie odcięta od lądu.",
        desc: "Jeden z cudów architektury średniowiecza w zatoce o największych przypływach w Europie (różnica poziomów wody sięga nawet 14 metrów)."
    },
    {
        name: "Grobla Olbrzyma / Giant's Causeway (Irlandia Północna)",
        lat: 55.2408,
        lng: -6.5116,
        continent: "Europa",
        category: "Geologia / Kolumny bazaltowe",
        easy: false,
        img: "img/giants_causeway.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Około 40 tysięcy ciasno przylegających do siebie wielokątnych kolumn bazaltowych schodzących wprost do morza.",
        desc: "Formacja powstała około 50-60 mln lat temu w wyniku gwałtownego stygnięcia lawy bazaltowej. Według legendy groblę ułożył mityczny celtycki olbrzym Finn McCool."
    },
    {
        name: "Klify Moheru (Hrabstwo Clare, Irlandia)",
        lat: 52.9715,
        lng: -9.4265,
        continent: "Europa",
        category: "Przyroda / Klify atlantyckie",
        easy: false,
        img: "img/cliffs_of_moher.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Ponad 200-metrowe pionowe ściany skalne ciągnące się wzdłuż wzburzonego Atlantyku na zachodnim krańcu Europy.",
        desc: "Jedna z najbardziej spektakularnych formacji brzegowych na świecie, zbudowana z warstw łupków i piaskowców, będąca siedliskiem tysięcy ptaków morskich, m.in. maskonurów."
    },
    {
        name: "Park Narodowy Jezior Plitwickich (Chorwacja)",
        lat: 44.8654,
        lng: 15.582,
        continent: "Europa",
        category: "Przyroda / Jeziora krasowe",
        easy: false,
        img: "img/plitvice.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Kaskadowy układ 16 turkusowych jezior połączonych setkami szumiących wodospadów pośród bujnych lasów.",
        desc: "Unikalny ekosystem krasowy w Górach Dynarskich, w którym naturalne tamy trawertynowe wciąż rosną i przekształcają bieg rzek i jezior."
    },
    {
        name: "Jezioro Bled (Słowenia)",
        lat: 46.3636,
        lng: 14.0938,
        continent: "Europa",
        category: "Przyroda / Krajobraz alpejski",
        easy: false,
        img: "img/lake_bled.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Alpejskie jezioro ze średniowiecznym zamkiem na stromej skale i jedyną naturalną wyspą w kraju z kościołem z Dzwonem Życzeń.",
        desc: "Malownicze jezioro polodowcowe w Alpach Julijskich, zasilane przez źródła termalne, słynące z tradycyjnych drewnianych łodzi pletna."
    },
    {
        name: "Krzywy Las (Nowe Czarnowo k. Gryfina, Polska)",
        lat: 53.2144,
        lng: 14.4764,
        continent: "Europa",
        category: "Przyroda / Osobliwość dendrologiczna",
        easy: false,
        img: "img/krzywy_las.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Niezwykłe skupisko około 100 sosen wygiętych tuż nad ziemią pod kątem 90 stopni w stronę północy.",
        desc: "Pomnik przyrody w województwie zachodniopomorskim, zasadzony prawdopodobnie w latach 30. XX wieku. Przyczyna wygięcia pni do dziś pozostaje fascynującą zagadką."
    },
    {
        name: "Morskie Oko (Tatry Wysokie, Polska)",
        lat: 49.1974,
        lng: 20.0712,
        continent: "Europa",
        category: "Przyroda / Jezioro karowe",
        easy: false,
        img: "img/morskie_oko.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Największe i najbardziej znane jezioro w polskich Tatrach, położone w Dolinie Rybiego Potoku u stóp Mięguszowieckich Szczytów i Rysów.",
        desc: "Jezioro polodowcowe karowo-morenowe na wysokości 1395 m n.p.m., o krystalicznie czystej wodzie, jedno z nielicznych naturalnie zarybionych jezior tatrzańskich."
    },
    {
        name: "Alhambra (Grenada, Andaluzja, Hiszpania)",
        lat: 37.1773,
        lng: -3.5881,
        continent: "Europa",
        category: "Architektura / Pałac mauretański",
        easy: false,
        img: "img/alhambra.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Ufortyfikowany kompleks pałacowy emirów z dynastii Nasrydów z kunsztownymi stiukami, fontannami i Dziedzińcem Lwów.",
        desc: "Szczytowe osiągnięcie architektury arabskiej w Europie, ostatni bastion Maurów na Półwyspie Iberyjskim, zdobyty przez królów katolickich w 1492 roku."
    },
    {
        name: "Trulli w Alberobello (Apulia, Włochy)",
        lat: 40.7838,
        lng: 17.2408,
        continent: "Europa",
        category: "Architektura / Domy stożkowe",
        easy: false,
        img: "img/trulli_alberobello.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Białe cylindryczne domki z wapienia wznoszone bez użycia zaprawy murarskiej, zwieńczone stożkowymi dachami z symbolami.",
        desc: "Tradycyjne budowle pasterskie i mieszkalne w dolinie Itria, budowane w taki sposób, by w razie kontroli poborców podatkowych można je było błyskawicznie rozebrać."
    },
    {
        name: "Zamek Eilean Donan (Szkocja, Wielka Brytania)",
        lat: 57.274,
        lng: -5.5161,
        continent: "Europa",
        category: "Średniowiecze / Zamek na wyspie",
        easy: false,
        img: "img/eilean_donan.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Kamienna twierdza klanu MacRae na małej wysepce połączonej kamiennym mostem u zbiegu trzech szkockich jezior.",
        desc: "Jeden z najczęściej fotografowanych zamków w Szkocji, położony w Highlands w drodze na wyspę Skye, znany z filmów 'Nieśmiertelny' i 'Świat to za mało'."
    },
    {
        name: "Geirangerfjord (Norwegia)",
        lat: 62.1015,
        lng: 7.094,
        continent: "Europa",
        category: "Przyroda / Fiord polodowcowy",
        easy: false,
        img: "img/geirangerfjord.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Głęboki błękitny fiord otoczony stromymi, ponadtysiącmetrowymi urwiskami i wodospadem Siedem Sióstr.",
        desc: "Wpisany na listę UNESCO fiord w regionie Møre og Romsdal, uznawany za jeden z najwspanialszych krajobrazów polodowcowych na naszej planecie."
    },
    {
        name: "Matterhorn / Monte Cervino (Szwajcaria / Włochy)",
        lat: 45.9765,
        lng: 7.6585,
        continent: "Europa",
        category: "Góry / Szczyt piramidalny",
        easy: false,
        img: "img/matterhorn.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Charakterystyczny, samotny szczyt w kształcie niemal idealnej czterobocznej piramidy o wysokości 4478 m n.p.m. nad Zermatt.",
        desc: "Jeden z najbardziej rozpoznawalnych szczytów świata w Alpach Pennińskich, symbol szwajcarskiej czekolady Toblerone i wielkie wyzwanie alpinizmu."
    },
    {
        name: "Hallstatt (Salzkammergut, Austria)",
        lat: 47.5622,
        lng: 13.6493,
        continent: "Europa",
        category: "Kultura / Wioska alpejska",
        easy: false,
        img: "img/hallstatt.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Zabytkowa wioska z drewnianą architekturą ściśnięta na wąskim skrawku lądu między jeziorem a stromym masywem Dachstein.",
        desc: "Kolebka epoki żelaza (kultura halsztacka) z najstarszą kopalnią soli na świecie, tak zachwycająca, że w Chinach wybudowano jej pełnowymiarową replikę."
    },
    {
        name: "Mury Obronne Dubrownika (Dalmacja, Chorwacja)",
        lat: 42.6412,
        lng: 18.1093,
        continent: "Europa",
        category: "Średniowiecze / Fortyfikacje miejskie",
        easy: false,
        img: "img/dubrovnik.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Niezdobyte kamienne mury obronne o długości niemal 2 km otaczające starówkę 'Perły Adriatyku'.",
        desc: "Potężny system baszt, fortów i murów wznoszony od XII do XVII wieku w dawnej Republice Raguzy, znany współcześnie także jako Królewska Przystań z Gry o Tron."
    },
    {
        name: "Kopalnia Soli 'Wieliczka' (Polska)",
        lat: 49.9831,
        lng: 20.0537,
        continent: "Europa",
        category: "Historia / Podziemna kopalnia soli",
        easy: false,
        img: "img/wieliczka.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Zabytkowa kopalnia soli kamiennej z monumentalną podziemną Kaplicą św. Kingi oświetloną solnymi żyrandolami.",
        desc: "Działająca nieprzerwanie od XIII wieku do końca XX wieku, jedna z najstarszych kopalni soli na świecie, wpisana na I listę UNESCO w 1978 roku."
    },
    {
        name: "Trolltunga / Język Trolla (Norwegia)",
        lat: 60.1242,
        lng: 6.74,
        continent: "Europa",
        category: "Geologia / Półka skalna",
        easy: false,
        img: "img/trolltunga.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Wąska, pozioma półka skalna wysunięta w przestrzeń 700 metrów ponad błękitną taflą jeziora Ringedalsvatnet.",
        desc: "Formacja polodowcowa powstała około 10 000 lat temu, gdy woda z topniejącego lodowca zamarzła w szczelinach góry i odłupała wielkie bloki skalne."
    },
    {
        name: "Błękitna Laguna / Blue Lagoon (Grindavík, Islandia)",
        lat: 63.8804,
        lng: -22.4495,
        continent: "Europa",
        category: "Geotermia / Baseny termalne",
        easy: false,
        img: "img/blue_lagoon.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Mlecznoniebieskie geotermalne uzdrowisko parujące pośród czarnego, postrzępionego pola lawy na półwyspie Reykjanes.",
        desc: "Woda bogata w krzemionkę i minerały ma stałą temperaturę 37-39°C i naturalnie odnawia się co 48 godzin dzięki sąsiedniej elektrowni geotermalnej Svartsengi."
    },
    {
        name: "Zamek Spiski / Spišský hrad (Żehra, Słowacja)",
        lat: 49.0019,
        lng: 20.7681,
        continent: "Europa",
        category: "Średniowiecze / Ruiny zamku",
        easy: false,
        img: "img/spis_castle.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Jedne z największych ruin zamkowych w Europie Środkowej, górujące na trawiastym wapiennym wzgórzu Spiszu.",
        desc: "Zamek wzniesiony na przełomie XI i XII wieku, zajmujący powierzchnię ponad 4 hektarów, stanowiący dawne centrum administracyjne i obronne Królestwa Węgier."
    },
    {
        name: "Błękitny Meczet / Sultanahmet (Stambuł, Turcja)",
        lat: 41.0054,
        lng: 28.9768,
        continent: "Azja",
        category: "Architektura / Świątynia osmańska",
        easy: false,
        img: "img/blue_mosque.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Monumentalna świątynia z 6 minaretami, której wnętrze zdobi ponad 20 tysięcy ręcznie malowanych ceramicznych płytek z Izniku.",
        desc: "Arcydzieło architektury osmańskiej wzniesione na początku XVII wieku z rozkazu sułtana Ahmeda I naprzeciwko bazyliki Hagia Sophia."
    },
    {
        name: "Sigirija / Lwia Skała (Sri Lanka)",
        lat: 7.957,
        lng: 80.7603,
        continent: "Azja",
        category: "Starożytność / Forteca na monolicie",
        easy: false,
        img: "img/sigiriya.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Starożytna forteca pałacowa króla Kassjapy na szczycie 200-metrowej pionowej bryły magmowej pośród dżungli.",
        desc: "Do ruin pałacu na szczycie prowadziły monumentalne schody wycięte między gigantycznymi łapami wykutego w skale lwa. Słynie też z fresków 'Niebiańskich Dziewic'."
    },
    {
        name: "Dolina Świątyń w Bagan (Mjanma / Birma)",
        lat: 21.1717,
        lng: 94.8585,
        continent: "Azja",
        category: "Starożytność / Buddyjskie pagody",
        easy: false,
        img: "img/bagan.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Równina nad rzeką Irawadi usiana ponad dwoma tysiącami ceglanych buddyjskich pagód, stup i klasztorów.",
        desc: "Stolica pierwszego Królestwa Paganu od IX do XIII wieku. W okresie największego rozkwitu na obszarze 100 km² wzniesiono ponad 10 tysięcy świątyń."
    },
    {
        name: "Pustynia Wadi Rum / Dolina Księżycowa (Jordania)",
        lat: 29.5734,
        lng: 35.4208,
        continent: "Azja",
        category: "Pustynia / Formacje piaskowcowe",
        easy: false,
        img: "img/wadi_rum.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Dolina pustynna z czerwonym piaskiem, naturalnymi łukami skalnymi i pionowymi masywami z granitu i piaskowca.",
        desc: "Słynny krajobraz związany z postacią Lawrence'a z Arabii, ze względu na swój pozaziemski wygląd wykorzystywany jako Mars w filmie 'Marsjanin'."
    },
    {
        name: "Wulkan Bromo (Wschodnia Jawa, Indonezja)",
        lat: -7.9425,
        lng: 112.953,
        continent: "Azja",
        category: "Wulkany / Kaldera Tengger",
        easy: false,
        img: "img/mount_bromo.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Dymiący aktywny krater wulkaniczny wyrastający pośrodku rozległego 'Morza Piasku' (Lautan Pasir).",
        desc: "Jeden z najbardziej aktywnych wulkanów Jawy o wysokości 2329 m n.p.m., święte miejsce dla miejscowego ludu Tengger, który składa w ofierze do krateru owoce i zwierzęta."
    },
    {
        name: "Złota Świątynia / Harmandir Sahib (Amritsar, Indie)",
        lat: 31.62,
        lng: 74.8765,
        continent: "Azja",
        category: "Architektura / Świątynia sikhijska",
        easy: false,
        img: "img/golden_temple.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Marmurowa świątynia pokryta setkami kilogramów czystego złota, stojąca pośrodku świętego zbiornika wodnego 'Amrit Sarovar'.",
        desc: "Najświętsze sanktuarium sikhizmu w Pendżabie. Prowadzi darmową kuchnię (langar), która codziennie karmi bezpłatnie ponad 100 tysięcy pielgrzymów bez względu na wyznanie czy kastę."
    },
    {
        name: "Góry Zhangjiajie / Kolumny Awatara (Hunan, Chiny)",
        lat: 29.3444,
        lng: 110.4792,
        continent: "Azja",
        category: "Geologia / Kwarcytowe iglice",
        easy: false,
        img: "img/zhangjiajie.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Ponad 3000 smukłych, kilkusetmetrowych filarów skalnych wyłaniających się z mgły w subtropikalnym lesie.",
        desc: "Niezwykłe formy wietrzenia piaskowców kwarcytowych, które posłużyły reżyserowi Jamesowi Cameronowi jako pierwowzór latających gór Hallelujah na planecie Pandora w filmie 'Avatar'."
    },
    {
        name: "Wzgórza Czekoladowe / Chocolate Hills (Bohol, Filipiny)",
        lat: 9.8297,
        lng: 124.1672,
        continent: "Azja",
        category: "Geologia / Kras stożkowy",
        easy: false,
        img: "img/chocolate_hills.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Ponad 1200 niemal identycznych, trawiastych pagórków stożkowych, które w porze suchej brązowieją niczym czekoladowe praliny.",
        desc: "Unikalna formacja geologiczna powstała z morskich osadów wapiennych i koralowych wypiętrzonych i zerodowanych przez tysiąclecia opadów deszczu."
    },
    {
        name: "Zamek Himeji / Zamek Białej Czapli (Hyogo, Japonia)",
        lat: 34.8394,
        lng: 134.6939,
        continent: "Azja",
        category: "Architektura / Zamek samurajski",
        easy: false,
        img: "img/himeji_castle.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Kunsztowny, wielopiętrowy zamek samurajski o lśniąco białych ścianach przypominających zrywającego się do lotu ptaka.",
        desc: "Najlepiej zachowany oryginalny drewniany zamek Japonii z początku XVII wieku, z labiryntem spiralnych bram i umocnień, który przetrwał nienaruszony bombardowania II wojny światowej."
    },
    {
        name: "Fushimi Inari-Taisha / Tysiąc Bram Torii (Kioto, Japonia)",
        lat: 34.9671,
        lng: 135.7727,
        continent: "Azja",
        category: "Kultura / Świątynia shinto",
        easy: false,
        img: "img/fushimi_inari.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Kilometry tuneli utworzonych z ponad 10 tysięcy cynobrowych bram torii wspinających się po zboczu świętej góry Inari.",
        desc: "Główna świątynia poświęcona bóstwu ryżu, rolnictwa i biznesu Inari, strzeżona przez setki kamiennych rzeźb lisów (kitsune) trzymających w pyskach klucze do spichlerzy."
    },
    {
        name: "Wielka Błękitna Dziura / Great Blue Hole (Belize)",
        lat: 17.3156,
        lng: -87.5344,
        continent: "Ameryka Północna",
        category: "Geologia / Podwodny lej krasowy",
        easy: false,
        img: "img/great_blue_hole.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Idealnie okrągła, ciemnogranatowa morska rozpadlina o średnicy ponad 300 m i głębokości 124 m w centrum rafy koralowej.",
        desc: "Zatopiona jaskinia krasowa z epoki lodowcowej, rozsławiona przez Jacques'a Cousteau jako jedno z dziesięciu najlepszych miejsc do nurkowania na Ziemi."
    },
    {
        name: "Kanion Antylopy / Antelope Canyon (Arizona, USA)",
        lat: 36.8619,
        lng: -111.3743,
        continent: "Ameryka Północna",
        category: "Geologia / Kanion szczelinowy",
        easy: false,
        img: "img/antelope_canyon.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Falisty, ciasny wąwóz w czerwonym piaskowcu oświetlany przez spektakularne pionowe snopy promieni słonecznych.",
        desc: "Święte miejsce Indian Nawaho (Navajo), wyrzeźbione przez tysiąclecia nagłych powodzi błyskawicznych w miękkim piaskowcu Navajo."
    },
    {
        name: "Monument Valley (Utah / Arizona, USA)",
        lat: 36.998,
        lng: -110.0985,
        continent: "Ameryka Północna",
        category: "Geologia / Ostańce pustynne",
        easy: false,
        img: "img/monument_valley.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Gigantyczne, samotne ostańce z czerwonego piaskowca (Mitten Buttes) wyrastające z płaskiej pustyni na terenie rezerwatu Nawaho.",
        desc: "Ikoniczny symbol Dzikiego Zachodu, sceneria klasycznych westernów Johna Forda i Johna Wayne'a oraz filmu 'Forrest Gump'."
    },
    {
        name: "Jezioro Moraine / Dolina Dziesięciu Szczytów (Banff, Kanada)",
        lat: 51.3217,
        lng: -116.186,
        continent: "Ameryka Północna",
        category: "Przyroda / Jezioro polodowcowe",
        easy: false,
        img: "img/lake_moraine.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Niewiarygodnie turkusowe jezioro górskie w kanadyjskich Górach Skalistych, otoczone dziesięcią strzelistymi szczytami.",
        desc: "Niezwykły, intensywnie niebieski kolor wody wynika ze zjawiska załamywania światła na drobinkach zawiesiny skalnej (mączki lodowcowej) zasilającej jezioro."
    },
    {
        name: "Gejzer Old Faithful (Park Narodowy Yellowstone, USA)",
        lat: 44.4605,
        lng: -110.8281,
        continent: "Ameryka Północna",
        category: "Geotermia / Gejzer stożkowy",
        easy: false,
        img: "img/yellowstone_geyser.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Najsłynniejszy gejzer na świecie, wyrzucający słup wrzącej wody na wysokość do 55 metrów z zegarmistrzowską regularnością co ok. 90 minut.",
        desc: "Odkryty w 1870 roku w najstarszym parku narodowym świata, położonym nad gigantyczną kalderą superwulkanu Yellowstone."
    },
    {
        name: "Piramida Słońca w Teotihuacan (Meksyk)",
        lat: 19.6925,
        lng: -98.8437,
        continent: "Ameryka Północna",
        category: "Starożytność / Piramida prekolumbijska",
        easy: false,
        img: "img/teotihuacan.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Jedna z największych piramid Mezoameryki (wysokość 65 m), stojąca przy monumentalnej Alei Zmarłych.",
        desc: "Centralna budowla 'Miasta Bogów', wzniesiona około II wieku n.e. przez tajemniczą cywilizację poprzedzającą Azteków o ponad tysiąc lat."
    },
    {
        name: "Park Narodowy Tikal (Peten, Gwatemala)",
        lat: 17.222,
        lng: -89.6237,
        continent: "Ameryka Północna",
        category: "Starożytność / Metropolia Majów",
        easy: false,
        img: "img/tikal.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Strome kamienne piramidy świątynne Majów wyrastające ponad gęsty, wiecznie zielony baldachim dżungli tropikalnej.",
        desc: "Jedno z najpotężniejszych królestw cywilizacji Majów okresu klasycznego, zamieszkiwane przez ponad 100 tysięcy ludzi, opuszczone w X wieku."
    },
    {
        name: "Kanion Sumidero (Chiapas, Meksyk)",
        lat: 16.8333,
        lng: -93.0833,
        continent: "Ameryka Północna",
        category: "Przyroda / Kanion rzeczny",
        easy: false,
        img: "img/sumidero_canyon.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Głęboki wąwóz rzeki Grijalva o niemal pionowych wapiennych ścianach sięgających 1000 metrów wysokości.",
        desc: "Kanion o unikalnym mikroklimacie, porośnięty lasem deszczowym z wodospadami (m.in. 'Drzewo Bożonarodzeniowe') i żyjącymi w rzece krokodylami."
    },
    {
        name: "Cenote Ik Kil (Jukatan, Meksyk)",
        lat: 20.6606,
        lng: -88.5503,
        continent: "Ameryka Północna",
        category: "Geologia / Studnia krasowa",
        easy: false,
        img: "img/cenote_ik_kil.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Głęboka, otwarta studnia wapienna wypełniona krystaliczną wodą, do której z powierzchni zwisają bujne liany i korzenie drzew.",
        desc: "Święta studnia Majów położona w pobliżu Chichen Itza, używana w starożytności do rytuałów religijnych ku czci boga deszczu Chaaka."
    },
    {
        name: "Salar de Uyuni (Boliwia)",
        lat: -20.1338,
        lng: -67.4891,
        continent: "Ameryka Południowa",
        category: "Geologia / Solnisko wysokogórskie",
        easy: false,
        img: "img/salar_de_uyuni.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Największe solnisko świata (ponad 10 tys. km²), które w porze deszczowej zamienia się w gigantyczne lustro idealnie odbijające niebo.",
        desc: "Pozostałość po wyschniętym prehistorycznym jeziorze na płaskowyżu Altiplano na wysokości 3653 m n.p.m., zawierające ponad połowę światowych rezerw litu."
    },
    {
        name: "Park Narodowy Torres del Paine (Patagonia, Chile)",
        lat: -51.2532,
        lng: -72.8814,
        continent: "Ameryka Południowa",
        category: "Góry / Granitowe iglice",
        easy: false,
        img: "img/torres_del_paine.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Trzy potężne pionowe iglice granitowe wznoszące się 2500 m ponad turkusowymi lodowcowymi jeziorami i wietrzną pampą.",
        desc: "Jeden z najbardziej dziewiczych parków narodowych Ameryki Południowej, słynący z lodowców Grey, rzeki Paine oraz stad dzikich gwanako i kondorów."
    },
    {
        name: "Góra Roraima / Tepui (Wenezuela / Brazylia / Gujana)",
        lat: 5.1433,
        lng: -60.7625,
        continent: "Ameryka Południowa",
        category: "Góry / Płaskowyż stołowy Tepui",
        easy: false,
        img: "img/mount_roraima.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Potężna góra stołowa z płaskim wierzchołkiem otoczona ze wszystkich stron pionowymi, 400-metrowymi urwiskami tonącymi w chmurach.",
        desc: "Najstarsze formacje geologiczne Ziemi (sprzed 2 miliardów lat), z unikalną endemiczną florą owadożerną, które zainspirowały powieść 'Zaginiony Świat' Arthura Conan Doyle'a."
    },
    {
        name: "Wodospad Salto Angel (Park Narodowy Canaima, Wenezuela)",
        lat: 5.9675,
        lng: -62.5356,
        continent: "Ameryka Południowa",
        category: "Przyroda / Najwyższy wodospad świata",
        easy: false,
        img: "img/angel_falls.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Najwyższy wodospad świata (979 metrów), spadający swobodnym strumieniem ze szczytu góry stołowej Auyantepui wprost do dziewiczej dżungli.",
        desc: "Woda spada z tak wielkiej wysokości, że zanim dotrze do dna doliny, w dużej mierze rozpyla się w mgłę chmurową. Nazwany na cześć amerykańskiego lotnika Jimmiego Angela."
    },
    {
        name: "Aleja Baobabów (Menabe, Madagaskar)",
        lat: -20.2508,
        lng: 44.4184,
        continent: "Afryka",
        category: "Przyroda / Monumentalne drzewa",
        easy: false,
        img: "img/baobab_avenue.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Grupa monumentalnych, 800-letnich baobabów Grandidiera o pniach przypominających kolumny, rosnących wzdłuż polnej drogi.",
        desc: "Niezwykły pomnik przyrody będący pozostałością po gęstym lesie tropikalnym, wykarczowanym pod pola uprawne. Baobaby magazynują w pniach tysiące litrów wody."
    },
    {
        name: "Kościół św. Jerzego w Lalibeli (Etiopia)",
        lat: 12.0319,
        lng: 39.0436,
        continent: "Afryka",
        category: "Starożytność / Kościół monolityczny",
        easy: false,
        img: "img/lalibela.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Średniowieczny kościół w kształcie równoramiennego krzyża greckiego, wykuty w całości w dół w litej skale wulkanicznej.",
        desc: "Jeden z 11 monolitycznych kościołów wzniesionych w XII-XIII wieku z rozkazu króla Lalibeli, który pragnął stworzyć 'Nową Jerozolimę' w górach Etiopii."
    },
    {
        name: "Wydmy Sossusvlei i Deadvlei (Pustynia Namib, Namibia)",
        lat: -24.7276,
        lng: 15.2928,
        continent: "Afryka",
        category: "Pustynia / Wydmy i biała glinka",
        easy: false,
        img: "img/sossusvlei.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Wyschnięte, spękane białe dno z martwymi 900-letnimi czarnymi drzewami akacjowymi, otoczone najwyższymi rdzawoczerwonymi wydmami świata.",
        desc: "Część najstarszej pustyni świata (Namib). Rdzawy kolor piasku pochodzi od tlenków żelaza, a wydmy (m.in. Big Daddy) osiągają ponad 300 metrów wysokości."
    },
    {
        name: "Piramidy w Meroe (Sudan)",
        lat: 16.9388,
        lng: 33.7497,
        continent: "Afryka",
        category: "Starożytność / Piramidy nubijskie",
        easy: false,
        img: "img/meroe_pyramids.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Dziesiątki stromych, wąskich piramid z czerwonego piaskowca wznoszących się pośród pustynnych wydm nad Nilem.",
        desc: "Nekropolia królów i królowych (kandake) starożytnego nubijskiego Królestwa Kusz, budowana od około 300 r. p.n.e. do 300 r. n.e."
    },
    {
        name: "Wielki Meczet w Dżenne (Mali)",
        lat: 13.9052,
        lng: -4.5552,
        continent: "Afryka",
        category: "Architektura / Budowla z suszonej gliny",
        easy: false,
        img: "img/djenne_mosque.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Największa na świecie budowla wzniesiona z suszonej na słońcu gliny (banco/adobe) z wystającymi drewnianymi belkami toron.",
        desc: "Arcydzieło architektury sudańsko-sahelyjskiej na wyspie na rzece Bani. Co roku cała społeczność miasta bierze udział w festiwalu ponownego tynkowania ścian meczetu świeżą gliną."
    },
    {
        name: "Dolina Królów (Teby Zachodnie, Luksor, Egipt)",
        lat: 25.7402,
        lng: 32.6014,
        continent: "Afryka",
        category: "Starożytność / Nekropolia faraonów",
        easy: false,
        img: "img/valley_of_the_kings.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Ukryta w pustynnym wąwozie skalnym nekropolia władców Nowego Państwa z bogato malowanymi grobowcami, w tym grobowcem Tutanchamona.",
        desc: "Miejsce spoczynku faraonów XVIII, XIX i XX dynastii (m.in. Ramzesa II i Setiego I), wykute głęboko w wapiennych skałach pod szczytem Al-Qurn przypominającym naturalną piramidę."
    },
    {
        name: "Depresja Danakilska / Wulkan Dallol (Kotlina Danakilska, Etiopia)",
        lat: 14.2417,
        lng: 40.2989,
        continent: "Afryka",
        category: "Geologia / Źródła hydrotermalne",
        easy: false,
        img: "img/dallol.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Jaskrawożółte, zielone i rdzawe wrzące baseny kwasowo-solne położone w depresji 120 metrów poniżej poziomu morza.",
        desc: "Jedno z najgorętszych i najbardziej ekstremalnych miejsc na Ziemi, ukształtowane przez intruzje magmowe reagujące z grubymi pokładami soli morskiej."
    },
    {
        name: "Dolina Geotermalna Te Puia (Rotorua, Nowa Zelandia)",
        lat: -38.1611,
        lng: 176.2547,
        continent: "Australia i Oceania",
        category: "Geotermia / Gejzer Pohutu",
        easy: false,
        img: "img/rotorua_geothermal.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Obszar aktywności wulkanicznej z bulgoczącymi basenami błotnymi i największym aktywnym gejzerem półkuli południowej Pohutu.",
        desc: "Serce kultury Maorysów w strefie wulkanicznej Taupo, gdzie ciepło geotermalne od wieków służy mieszkańcom do gotowania i ogrzewania domostw."
    },
    {
        name: "Wioska Hobbiton (Matamata, Nowa Zelandia)",
        lat: -37.8721,
        lng: 175.6829,
        continent: "Australia i Oceania",
        category: "Kultura / Plan filmowy Shire",
        easy: false,
        img: "img/hobbiton.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Malownicze zielone wzgórza z 44 norkami hobbitów o okrągłych kolorowych drzwiach i gospodą 'Pod Zielonym Smokiem'.",
        desc: "Oryginalny plan filmowy trylogii 'Władca Pierścieni' i 'Hobbit' Petera Jacksona, zachowany na stałe pośród farmy owiec w regionie Waikato."
    },
    {
        name: "Zamek Eltz (Nadrenia-Palatynat, Niemcy)",
        lat: 50.2052,
        lng: 7.3366,
        continent: "Europa",
        category: "Średniowiecze / Zamek rycerski",
        easy: false,
        img: "img/burg_eltz.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Bajkowy średniowieczny zamek ukryty w gęstym lesie w dolinie rzeki Elzbach, w rękach tej samej rodziny od ponad 800 lat.",
        desc: "Jeden z nielicznych zamków nad Renem i Mozelą, który nigdy nie został zdobyty ani zniszczony. Składa się z 8 wież mieszkalnych wznoszących się na 35-metrowej skale."
    },
    {
        name: "Preikestolen / Ambona (Ryfylke, Norwegia)",
        lat: 58.9864,
        lng: 6.1887,
        continent: "Europa",
        category: "Geologia / Klif fiordowy",
        easy: false,
        img: "img/preikestolen.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Płaska, kwadratowa półka skalna o wymiarach 25x25 metrów, zawieszona 604 metry pionowo nad wodami Lysefjordu.",
        desc: "Monumentalny klif polodowcowy w południowo-zachodniej Norwegii, powstały około 10 tysięcy lat temu w wyniku pęknięcia skał pod naporem lodu."
    },
    {
        name: "Zamek Czocha (Sucha, Dolny Śląsk, Polska)",
        lat: 51.0309,
        lng: 15.3039,
        continent: "Europa",
        category: "Średniowiecze / Zamek obronny",
        easy: false,
        img: "img/zamek_czocha.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Mroczna twierdza warowna na granitowej skale nad Jeziorem Leśniańskim, pełna tajnych przejść i legend o skarbach.",
        desc: "Zamek obronny z XIII wieku, przebudowany na początku XX wieku na romantyczną rezydencję. Nazywany 'polskim Hogwartem' ze względu na tajemniczą atmosferę i liczne labirynty."
    },
    {
        name: "Zamek w Chambord (Dolina Loary, Francja)",
        lat: 47.6161,
        lng: 1.5172,
        continent: "Europa",
        category: "Renesans / Pałac królewski",
        easy: false,
        img: "img/chambord.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Największy renesansowy pałac myśliwski w Dolinie Loary, słynący z podwójnej spiralnej klatki schodowej zaprojektowanej przez Leonarda da Vinci.",
        desc: "Monumentalna rezydencja króla Franciszka I z 440 komnatami i dachem usianym setkami wieżyczek, kominów i iglic, otoczona największym ogrodzonym parkiem leśnym w Europie."
    },
    {
        name: "Stari Most / Stary Most w Mostarze (Bośnia i Hercegowina)",
        lat: 43.3373,
        lng: 17.815,
        continent: "Europa",
        category: "Architektura / Most osmański",
        easy: false,
        img: "img/stari_most.jpg",
        license: "Wikimedia Commons / CC",
        clue: "XVI-wieczny kamienny most łukowy przerzucony nad szmaragdową rzeką Neretwą, symbol pojednania i tradycyjnych skoków do wody.",
        desc: "Arcydzieło architektury osmańskiej wzniesione przez Mimara Hajrudina w 1566 roku. Zniszczony podczas wojny w 1993 roku i wiernie odbudowany z oryginalnych bloków tenelii w 2004 roku."
    },
    {
        name: "Skalne Miasto Adrszpach (Góry Stołowe, Czechy)",
        lat: 50.6139,
        lng: 16.1242,
        continent: "Europa",
        category: "Geologia / Labirynt piaskowcowy",
        easy: false,
        img: "img/adrspach_rocks.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Fantastyczny labirynt wąskich kanionów i strzelistych wież z piaskowca z Gotycką Bramą i szmaragdowym jeziorkiem.",
        desc: "Narodowy rezerwat przyrody w czeskiej części Gór Stołowych, uformowany przez miliony lat erozji dawnego dna morskiego, z formacjami takimi jak 'Kochankowie' czy 'Głowa Cukru'."
    },
    {
        name: "Wodospad Dettifoss (Park Narodowy Vatnajökull, Islandia)",
        lat: 65.8147,
        lng: -16.3846,
        continent: "Europa",
        category: "Cuda Natury / Wodospad polodowcowy",
        easy: false,
        img: "img/dettifoss.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Najpotężniejszy pod względem energii i przepływu wodospad Europy, grzmiący w surowym kanionie Jökulsárgljúfur.",
        desc: "Wodospad o szerokości 100 m i wysokości 44 m, przez który przetacza się średnio 200–500 m³ szarej, polodowcowej wody na sekundę, wykorzystany w scenie otwierającej film 'Prometeusz'."
    },
    {
        name: "Zamek Peleş (Sinaia, Karpaty, Rumunia)",
        lat: 45.3599,
        lng: 25.5427,
        continent: "Europa",
        category: "Architektura / Pałac neorenesansowy",
        easy: false,
        img: "img/peles_castle.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Bajkowa, ryglowa rezydencja królów Rumunii w stylu niemieckiego neorenesansu, ukryta pośród jodłowych lasów Karpat.",
        desc: "Letnia rezydencja króla Karola I Hohenzollerna, wzniesiona pod koniec XIX wieku. Był to pierwszy w Europie zamek w całości zelektryfikowany, posiadający centralne ogrzewanie i windę."
    },
    {
        name: "Wrota Piekieł / Krater Darvaza (Pustynia Kara-kum, Turkmenistan)",
        lat: 40.2525,
        lng: 58.4397,
        continent: "Azja",
        category: "Osobliwość / Płonący krater gazowy",
        easy: false,
        img: "img/darvaza_crater.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Głęboka na 30 metrów rozpadlina w sercu pustyni, z której nieprzerwanie od ponad 50 lat buchają płomienie płonącego gazu ziemnego.",
        desc: "Krater powstał w 1971 roku po zawaleniu się radzieckiej platformy wiertniczej. Aby uniknąć ulatniania się trującego metanu, gaz podpalono – spodziewano się, że wypali się w kilka tygodni, lecz płonie do dziś."
    },
    {
        name: "Kolorowe Góry Zhangye Danxia (Gansu, Chiny)",
        lat: 38.9056,
        lng: 100.1294,
        continent: "Azja",
        category: "Geologia / Tęczowe góry",
        easy: false,
        img: "img/zhangye_danxia.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Niezwykłe pasma górskie mieniące się jaskrawymi, tęczowymi pasami czerwieni, żółci i zieleni niczym malowany pejzaż.",
        desc: "Formacje powstały w ciągu 24 milionów lat z warstw czerwonego piaskowca i minerałów prasowanych pod wpływem ruchów tektonicznych, a następnie wyrzeźbionych przez wiatr i deszcz."
    },
    {
        name: "Wielki Budda z Leshan (Syczuan, Chiny)",
        lat: 29.5447,
        lng: 103.7694,
        continent: "Azja",
        category: "Starożytność / Posąg wykuty w skale",
        easy: false,
        img: "img/leshan_giant_buddha.jpg",
        license: "Wikimedia Commons / CC",
        clue: "71-metrowy kamienny posąg siedzącego Buddy Majtrei, wykuty w VIII wieku w pionowym nadrzecznym klifie z piaskowca.",
        desc: "Największy kamienny Budda na świecie, wzniesiony u zbiegu trzech rzek z inicjatywy mnicha Hai Tonga, który wierzył, że posąg uspokoi wzburzone i niebezpieczne dla łodzi wody."
    },
    {
        name: "Wielki Meczet Szejka Zayeda (Abu Zabi, ZEA)",
        lat: 24.4128,
        lng: 54.4749,
        continent: "Azja",
        category: "Architektura / Meczet współczesny",
        easy: false,
        img: "img/sheikh_zayed_mosque.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Śnieżnobiały, monumentalny kompleks z białego marmuru macedońskiego z 82 kopułami i największym ręcznie tkanym dywanem świata.",
        desc: "Jeden z najwspanialszych i największych meczetów współczesnego świata islamskiego, mogący pomieścić 40 tysięcy wiernych, ozdobiony 24-karatowym złotem i kryształami Swarovskiego."
    },
    {
        name: "Kamienny Las Shilin (Junnan, Chiny)",
        lat: 24.8189,
        lng: 103.3247,
        continent: "Azja",
        category: "Geologia / Kras wieżowy",
        easy: false,
        img: "img/stone_forest_shilin.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Rozległy labirynt szarych, ostrych ostańców wapiennych przypominających skamieniałe drzewa wyrastające z ziemi.",
        desc: "Krasowy cud natury sprzed 270 milionów lat, gdy obszar ten był dnem płytkiego oceanu. Według legendy ludu Yi las powstał z niespełnionej miłości pięknej dziewczyny Ashimy."
    },
    {
        name: "Błękitne Miasto Szefszawan / Chefchaouen (Góry Rif, Maroko)",
        lat: 35.1688,
        lng: -5.2636,
        continent: "Afryka",
        category: "Architektura / Miasto błękitne",
        easy: false,
        img: "img/chefchaouen.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Górska medyna, której wszystkie domy, schody, mury i drzwi pomalowane są na kojące, intensywne odcienie błękitu i indygo.",
        desc: "Tradycję malowania ścian na niebiesko zapoczątkowali żydowscy uchodźcy z Andaluzji w XV wieku, dla których kolor ten symbolizował niebo i obecność Boga."
    },
    {
        name: "Blyde River Canyon i Three Rondavels (Mpumalanga, RPA)",
        lat: -24.5772,
        lng: 30.8142,
        continent: "Afryka",
        category: "Cuda Natury / Zielony kanion",
        easy: false,
        img: "img/blyde_river_canyon.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Jeden z największych i najbardziej zielonych kanionów świata ze spektakularnymi formacjami skalnymi przypominającymi tradycyjne okrągłe chaty.",
        desc: "Głęboki na 800 metrów kanion z czerwonego piaskowca porośnięty bujną podzwrotnikową roślinnością, stanowiący część skarpy Drakensberg."
    },
    {
        name: "Różowe Jezioro / Jezioro Retba (Senegal)",
        lat: 14.8392,
        lng: -17.2347,
        continent: "Afryka",
        category: "Przyroda / Jezioro różowe i solnisko",
        easy: false,
        img: "img/lake_retba.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Jaskraworóżowe słone jezioro oddzielone od Atlantyku wąskim pasem wydm, w którym wydobywa się sól metodami tradycyjnymi.",
        desc: "Niezwykły różowo-fioletowy kolor wody wynika z obecności halofilnych mikroalg Dunaliella salina produkujących czerwony barwnik, a zasolenie dochodzi do 40% (więcej niż w Morzu Martwym)."
    },
    {
        name: "Rezerwat Tsingy de Bemaraha (Madagaskar)",
        lat: -18.79,
        lng: 44.71,
        continent: "Afryka",
        category: "Geologia / Krasowe iglice wapienne",
        easy: false,
        img: "img/tsingy_bemaraha.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Niedostępny las ostrych jak brzytwa, pionowych wapiennych iglic skalnych połączonych mostami wiszącymi w zachodnim Madagaskarze.",
        desc: "Słowo 'tsingy' w języku malgaskim oznacza 'miejsce, gdzie nie da się chodzić boso'. Ten unikalny kras krasowy jest domem dla wielu endemicznych gatunków lemurów i ptaków."
    },
    {
        name: "El Capitan i Dolina Yosemite (Kalifornia, USA)",
        lat: 37.734,
        lng: -119.6377,
        continent: "Ameryka Północna",
        category: "Góry / Granitowy monolit",
        easy: false,
        img: "img/yosemite_el_capitan.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Potężna, pionowa ściana z litego granitu o wysokości ponad 900 metrów, mekka wspinaczy z całego świata.",
        desc: "Najbardziej znany monolit polodowcowy w Parku Narodowym Yosemite, słynący z legendarnej drogi wspinaczkowej 'The Nose' oraz pierwszego w historii przejścia free solo przez Alexa Honnolda w 2017 r."
    },
    {
        name: "Krater Meteorytowy / Barringera (Arizona, USA)",
        lat: 35.0275,
        lng: -111.0228,
        continent: "Ameryka Północna",
        category: "Kosmologia / Krater uderzeniowy",
        easy: false,
        img: "img/meteor_crater.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Najlepiej zachowany krater uderzeniowy na Ziemi o średnicy 1200 metrów i głębokości 170 metrów na płaskiej pustyni w Arizonie.",
        desc: "Powstał około 50 000 lat temu w wyniku uderzenia żelazowo-niklowego meteorytu o średnicy 50 metrów pędzącego z prędkością kilkunastu kilometrów na sekundę."
    },
    {
        name: "Cenote Dos Ojos / Dwoje Oczu (Jukatan, Meksyk)",
        lat: 20.3242,
        lng: -87.3922,
        continent: "Ameryka Północna",
        category: "Geologia / Podwodny system jaskiniowy",
        easy: false,
        img: "img/cenote_dos_ojos.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Dwa połączone ze sobą podziemne zapadliska krasowe o niewiarygodnie krystalicznej wodzie i tysiącach stalaktytów.",
        desc: "Część jednego z najdłuższych podwodnych systemów jaskiniowych na świecie (Sac Actun), sięgającego ponad 300 km długości korytarzy, popularna wśród nurków jaskiniowych."
    },
    {
        name: "Semuc Champey (Alta Verapaz, Gwatemala)",
        lat: 15.5342,
        lng: -89.9622,
        continent: "Ameryka Północna",
        category: "Przyroda / Baseny trawertynowe w dżungli",
        easy: false,
        img: "img/semuc_champey.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Naturalny 300-metrowy most wapienny w sercu lasu mglistego, na którym ułożyły się kaskady szmaragdowo-turkusowych basenów.",
        desc: "Pod kamiennym mostem z basenami przepływa z rykiem podziemna rzeka Cahabón, tworząc jedno z najbardziej urokliwych i ukrytych miejsc w Ameryce Środkowej."
    },
    {
        name: "Tęczowa Góra / Vinicunca (Andy, Peru)",
        lat: -13.8694,
        lng: -71.3031,
        continent: "Ameryka Południowa",
        category: "Góry / Pasy mineralne",
        easy: false,
        img: "img/vinicunca_rainbow_mountain.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Wysokogórski szczyt w Andach (5200 m n.p.m.) w pasy złota, lawendy, turkusu i czerwieni, odsłonięty po stopnieniu lodowca.",
        desc: "Niezwykłe ubarwienie góry to wynik milionów lat sedymentacji i wietrzenia 14 różnych minerałów (w tym związków żelaza, miedzi i siarki). Stała się światowym fenomenem turystycznym po 2015 roku."
    },
    {
        name: "Kanion Colca (Arequipa, Peru)",
        lat: -15.6,
        lng: -71.8833,
        continent: "Ameryka Południowa",
        category: "Cuda Natury / Głęboki kanion andyjski",
        easy: false,
        img: "img/colca_canyon.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Jeden z najgłębszych kanionów na Ziemi (ponad 3200 m głębokości), po raz pierwszy zdobyty i spłynięty przez polskich kajakarzy w 1981 roku.",
        desc: "Kanion jest dwukrotnie głębszy od Wielkiego Kanionu Kolorado. W punkcie widokowym Cruz del Cóndor można z bliska podziwiać majestatyczne kondory wielkie szybujące w prądach termicznych."
    },
    {
        name: "Wodospad Kaieteur (Park Narodowy Kaieteur, Gujana)",
        lat: 5.1761,
        lng: -59.48,
        continent: "Ameryka Południowa",
        category: "Cuda Natury / Wodospad jednouskokowy",
        easy: false,
        img: "img/kaieteur_falls.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Największy na świecie wodospad o pojedynczym spadku wody (226 metrów) pod względem objętości, ukryty w dziewiczej puszczy amazońskiej.",
        desc: "Wodospad na rzece Potaro jest niemal pięciokrotnie wyższy od Niagary i dwukrotnie wyższy od Wodospadów Wiktorii, otoczony dziewiczym lasem deszczowym z endemicznymi złotymi żabkami."
    },
    {
        name: "Caño Cristales / Rzeka Pięciu Kolorów (Serranía de la Macarena, Kolumbia)",
        lat: 2.2642,
        lng: -73.7886,
        continent: "Ameryka Południowa",
        category: "Przyroda / Kolorowa rzeka",
        easy: false,
        img: "img/cano_cristales.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Płynna tęcza – rzeka, której skaliste koryto od lipca do listopada mieni się jaskrawą purpurą, fuksją, żółcią i zielenią.",
        desc: "Zjawiskowy spektakl barw tworzy endemiczna roślina wodna Macarenia clavigera, która pod wpływem odpowiedniego nasłonecznienia i poziomu krystalicznie czystej wody zakwita intensywną czerwienią."
    },
    {
        name: "Dwunastu Apostołów / Twelve Apostles (Wiktoria, Australia)",
        lat: -38.6658,
        lng: 143.1053,
        continent: "Australia i Oceania",
        category: "Przyroda / Wapienne kolumny morskie",
        easy: false,
        img: "img/twelve_apostles.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Monumentalne wapienne kolumny i ostańce wyłaniające się ze spienionych fal Oceanu Południowego wzdłuż Great Ocean Road.",
        desc: "Kolumny o wysokości do 50 metrów powstały przez erozję miękkich klifów wapiennych. Mimo nazwy 'Dwunastu Apostołów' pierwotnie było ich dziewięć, a fale nieustannie podmywają ich podstawy."
    },
    {
        name: "Pustynia Pinnacles (Park Narodowy Nambung, Australia Zachodnia)",
        lat: -30.6033,
        lng: 115.1561,
        continent: "Australia i Oceania",
        category: "Geologia / Wapienne filary pustynne",
        easy: false,
        img: "img/pinnacles_desert.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Tysiące tajemniczych, kilkumetrowych wapiennych filarów i iglic wyrastających z ruchomych żółtych piasków nad brzegiem Oceanu Indyjskiego.",
        desc: "Struktury powstały z wapiennych muszli morskich naniesionych przez wiatr tysiące lat temu, a następnie spojonych i wypreparowanych przez erozję roślinności i deszczu."
    },
    {
        name: "Jezioro Hillier (Middle Island, Australia Zachodnia)",
        lat: -34.095,
        lng: 123.2033,
        continent: "Australia i Oceania",
        category: "Przyroda / Różowe jezioro bezodpływowe",
        easy: false,
        img: "img/lake_hillier.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Niezwykłe jezioro o trwałej barwie jaskrawej gumy balonowej, otoczone ciemnozielonym pasem lasu eukaliptusowego i błękitem oceanu.",
        desc: "W przeciwieństwie do innych różowych jezior, woda z Jeziora Hillier nie traci swojej pasteloworóżowej barwy nawet po nabraniu do przezroczystej szklanki."
    },
    {
        name: "Jaskinie Waitomo Glowworm (Wyspa Północna, Nowa Zelandia)",
        lat: -38.2614,
        lng: 175.1036,
        continent: "Australia i Oceania",
        category: "Przyroda / Bioluminescencyjne jaskinie",
        easy: false,
        img: "img/waitomo_caves.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Podziemna jaskinia krasowa, której sklepienie rozświetlają tysiące błękitnych punkcików niczym rozgwieżdżone nocne niebo.",
        desc: "Magiczne światło emitują larwy endemicznego nowozelandzkiego grzybiarka Arachnocampa luminosa, które zwieszają z sufitu lepkie, świecące nici w celu wabienia owadów."
    },
    {
        name: "Szmaragdowe Jeziora w Parku Narodowym Tongariro (Nowa Zelandia)",
        lat: -39.1333,
        lng: 175.65,
        continent: "Australia i Oceania",
        category: "Wulkany / Jeziora kraterowe",
        easy: false,
        img: "img/tongariro_emerald_lakes.jpg",
        license: "Wikimedia Commons / CC",
        clue: "Trzy jaskrawo szmaragdowo-turkusowe jeziora wypełniające stare kratery wulkaniczne pośród siarkowych dymów i czarnej lawy.",
        desc: "Niewiarygodny kolor wód jezior Ngarotopounamu wynika z rozpuszczonych minerałów wulkanicznych wymywanych ze skał przez kwaśne wody termalne na trasie Tongariro Alpine Crossing."
    }
];
